import sys

inFile=sys.argv[1]
outFile=sys.argv[2]

with open(inFile,"rb") as f:
	data=f.read()

with open(outFile,"wt") as f:
	print >>f,"//Autogenerated do not modify"
	#print >>f,"const uint8_t pn73x_flash_write_code[]={\n"
	out=[ "0x%02x" % ord(d) for d in data]
	pos=0
	llen=32
	while pos<len(out):
		print >>f,"\t%s," % ( ",".join(out[pos:pos+llen]) )
		pos+=llen
	#print >>f,"};"
	